" Go
set rtp+=$HOME/projects/go/misc/vim

" General
set history=1000

filetype plugin indent on
syntax on

" Reload file if it is changed from outside
set autoread
set ruler

set ignorecase
set smartcase " Ignore ignorecase if upper chars are in search string

set hlsearch
set incsearch

set magic
set showmatch
set mat=2

set wildmode=list:longest,full
set wildmenu

set noerrorbells
set novisualbell
set t_vb=

set gfn=Inconsolata:h20
set t_Co=256
colorscheme railscasts 

if has("gui_running")
  set guioptions-=T
end

set background=dark
set nonu

set encoding=utf8
set ffs=unix,dos,mac
  
set backupdir=~/.vim/tmp
set undodir=~/.vim/tmp/undo
set undofile

set expandtab
set tabstop=2
set shiftwidth=2
set smarttab

set lbr

set ai
set si
set wrap

